import json

# Load the notebook
with open('Rural_Urban_Adoption_Analysis.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find and update the interactive cell
for i, cell in enumerate(nb['cells']):
    if cell.get('cell_type') == 'code' and any('ipywidgets' in line for line in cell.get('source', [])):
        # Update with complete dependency checking
        cell['source'] = [
            "# Import interactive widgets\n",
            "try:\n",
            "    from ipywidgets import interact, widgets\n",
            "    from IPython.display import display, clear_output\n",
            "    \n",
            "    # Ensure area_type column exists in df_enrollment\n",
            "    if 'area_type' not in df_enrollment.columns:\n",
            "        print(\"⚠ Applying pincode classification first...\")\n",
            "        df_enrollment['area_type'] = df_enrollment['pincode'].apply(classify_pincode)\n",
            "        print(\"✓ Classification applied to enrollment data\")\n",
            "    \n",
            "    # Create df_enroll_clean if it doesn't exist\n",
            "    if 'df_enroll_clean' not in globals():\n",
            "        df_enroll_clean = df_enrollment[df_enrollment['area_type'] != 'Unknown'].copy()\n",
            "        print(\"✓ Created df_enroll_clean variable\")\n",
            "    \n",
            "    # Get list of unique states\n",
            "    state_list = sorted(df_enroll_clean['state'].unique().tolist())\n",
            "    \n",
            "    def analyze_state(selected_state):\n",
            "        clear_output(wait=True)\n",
            "        \n",
            "        # Filter data for selected state\n",
            "        state_data = df_enroll_clean[df_enroll_clean['state'] == selected_state]\n",
            "        \n",
            "        if len(state_data) == 0:\n",
            "            print(f\"No data available for {selected_state}\")\n",
            "            return\n",
            "        \n",
            "        print(\"=\" * 80)\n",
            "        print(f\"ANALYSIS FOR: {selected_state.upper()}\")\n",
            "        print(\"=\" * 80)\n",
            "        \n",
            "        # Area type distribution\n",
            "        area_dist = state_data.groupby('area_type')[['age_0_5', 'age_5_17', 'age_18_greater']].sum()\n",
            "        area_dist['total'] = area_dist.sum(axis=1)\n",
            "        \n",
            "        print(\"\\nEnrollment by Area Type:\")\n",
            "        print(area_dist)\n",
            "        \n",
            "        # Calculate percentages\n",
            "        if 'Rural' in area_dist.index and 'Urban' in area_dist.index:\n",
            "            rural_pct = (area_dist.loc['Rural', 'total'] / area_dist['total'].sum() * 100)\n",
            "            urban_pct = (area_dist.loc['Urban', 'total'] / area_dist['total'].sum() * 100)\n",
            "            print(f\"\\n📊 Rural: {rural_pct:.2f}% | Urban: {urban_pct:.2f}%\")\n",
            "        elif 'Rural' in area_dist.index:\n",
            "            print(f\"\\n📊 Rural: 100.00% | Urban: 0.00%\")\n",
            "        elif 'Urban' in area_dist.index:\n",
            "            print(f\"\\n📊 Rural: 0.00% | Urban: 100.00%\")\n",
            "        \n",
            "        # Top districts\n",
            "        print(\"\\n\" + \"=\" * 80)\n",
            "        print(\"TOP 10 DISTRICTS BY ENROLLMENT\")\n",
            "        print(\"=\" * 80)\n",
            "        district_totals = state_data.groupby(['district', 'area_type'])['age_18_greater'].sum().reset_index()\n",
            "        district_totals = district_totals.sort_values('age_18_greater', ascending=False).head(10)\n",
            "        print(district_totals.to_string(index=False))\n",
            "        \n",
            "        # Visualization\n",
            "        fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n",
            "        \n",
            "        # Plot 1: Area type distribution\n",
            "        if len(area_dist) > 0:\n",
            "            colors = ['#27ae60' if idx == 'Rural' else '#e67e22' for idx in area_dist.index]\n",
            "            area_dist['total'].plot(kind='bar', ax=axes[0], color=colors)\n",
            "            axes[0].set_title(f'{selected_state.title()} - Total Enrollment by Area Type', \n",
            "                            fontsize=13, fontweight='bold')\n",
            "            axes[0].set_xlabel('Area Type', fontsize=11)\n",
            "            axes[0].set_ylabel('Total Enrollments', fontsize=11)\n",
            "            axes[0].tick_params(axis='x', rotation=0)\n",
            "            axes[0].grid(axis='y', alpha=0.3)\n",
            "            \n",
            "            # Add value labels\n",
            "            for idx, v in enumerate(area_dist['total']):\n",
            "                axes[0].text(idx, v, f'{int(v):,}', ha='center', va='bottom', fontweight='bold', fontsize=9)\n",
            "        \n",
            "        # Plot 2: Age distribution\n",
            "        if len(area_dist) > 0:\n",
            "            area_dist[['age_0_5', 'age_5_17', 'age_18_greater']].plot(kind='bar', ax=axes[1])\n",
            "            axes[1].set_title(f'{selected_state.title()} - Age-wise Enrollment Distribution', \n",
            "                            fontsize=13, fontweight='bold')\n",
            "            axes[1].set_xlabel('Area Type', fontsize=11)\n",
            "            axes[1].set_ylabel('Enrollments', fontsize=11)\n",
            "            axes[1].tick_params(axis='x', rotation=0)\n",
            "            axes[1].legend(['Age 0-5', 'Age 5-17', 'Age 18+'], loc='best', fontsize=9)\n",
            "            axes[1].grid(axis='y', alpha=0.3)\n",
            "        \n",
            "        plt.tight_layout()\n",
            "        plt.show()\n",
            "    \n",
            "    # Create dropdown widget\n",
            "    state_dropdown = widgets.Dropdown(\n",
            "        options=state_list,\n",
            "        value=state_list[0] if state_list else None,\n",
            "        description='Select State:',\n",
            "        style={'description_width': 'initial'},\n",
            "        layout=widgets.Layout(width='400px')\n",
            "    )\n",
            "    \n",
            "    # Create analyze button\n",
            "    analyze_button = widgets.Button(\n",
            "        description='Analyze State',\n",
            "        button_style='success',\n",
            "        tooltip='Click to analyze selected state',\n",
            "        icon='chart-bar'\n",
            "    )\n",
            "    \n",
            "    output_area = widgets.Output()\n",
            "    \n",
            "    def on_button_click(b):\n",
            "        with output_area:\n",
            "            analyze_state(state_dropdown.value)\n",
            "    \n",
            "    analyze_button.on_click(on_button_click)\n",
            "    \n",
            "    # Display widgets\n",
            "    print(\"=\"*80)\n",
            "    print(\"INTERACTIVE STATE-WISE ANALYSIS\")\n",
            "    print(\"=\"*80)\n",
            "    print(f\"✓ {len(state_list)} states available for analysis\")\n",
            "    print(\"\\nSelect a state from the dropdown and click 'Analyze State' to view detailed insights.\\n\")\n",
            "    \n",
            "    display(widgets.HBox([state_dropdown, analyze_button]))\n",
            "    display(output_area)\n",
            "    \n",
            "except ImportError:\n",
            "    print(\"⚠ ipywidgets not available. Install with: !pip install ipywidgets\")\n",
            "    print(\"\\nAlternatively, use the manual function below:\")\n",
            "    \n",
            "    # Ensure area_type column exists\n",
            "    if 'area_type' not in df_enrollment.columns:\n",
            "        df_enrollment['area_type'] = df_enrollment['pincode'].apply(classify_pincode)\n",
            "        print(\"✓ Classification applied\")\n",
            "    \n",
            "    # Create df_enroll_clean\n",
            "    df_enroll_clean = df_enrollment[df_enrollment['area_type'] != 'Unknown'].copy()\n",
            "    \n",
            "    # Manual function\n",
            "    def analyze_state_manual(selected_state):\n",
            "        \"\"\"Manually analyze a specific state. Usage: analyze_state_manual('state_name')\"\"\"\n",
            "        state_data = df_enroll_clean[df_enroll_clean['state'] == selected_state]\n",
            "        \n",
            "        if len(state_data) == 0:\n",
            "            print(f\"No data available for {selected_state}\")\n",
            "            return\n",
            "        \n",
            "        print(\"=\" * 80)\n",
            "        print(f\"ANALYSIS FOR: {selected_state.upper()}\")\n",
            "        print(\"=\" * 80)\n",
            "        \n",
            "        area_dist = state_data.groupby('area_type')[['age_0_5', 'age_5_17', 'age_18_greater']].sum()\n",
            "        area_dist['total'] = area_dist.sum(axis=1)\n",
            "        \n",
            "        print(\"\\nEnrollment by Area Type:\")\n",
            "        display(area_dist)\n",
            "        \n",
            "        # Visualizations\n",
            "        fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n",
            "        \n",
            "        if len(area_dist) > 0:\n",
            "            colors = ['#27ae60' if idx == 'Rural' else '#e67e22' for idx in area_dist.index]\n",
            "            area_dist['total'].plot(kind='bar', ax=axes[0], color=colors)\n",
            "            axes[0].set_title(f'{selected_state.title()} - Enrollment by Area', fontsize=12)\n",
            "            axes[0].set_xlabel('Area Type')\n",
            "            axes[0].tick_params(axis='x', rotation=0)\n",
            "            \n",
            "            area_dist[['age_0_5', 'age_5_17', 'age_18_greater']].plot(kind='bar', ax=axes[1])\n",
            "            axes[1].set_title(f'{selected_state.title()} - Age Distribution', fontsize=12)\n",
            "            axes[1].legend(['Age 0-5', 'Age 5-17', 'Age 18+'])\n",
            "            axes[1].tick_params(axis='x', rotation=0)\n",
            "        \n",
            "        plt.tight_layout()\n",
            "        plt.show()\n",
            "    \n",
            "    # Show available states\n",
            "    available_states = sorted(df_enroll_clean['state'].unique().tolist())\n",
            "    print(f\"\\n📍 Example: analyze_state_manual('{available_states[0]}')\")\n",
            "    print(f\"\\n📋 Available states ({len(available_states)}):\")\n",
            "    for i, state in enumerate(available_states, 1):\n",
            "        print(f\"  {i}. {state}\")"
        ]
        print(f"✓ Updated cell {i}")
        break

# Save the modified notebook
with open('Rural_Urban_Adoption_Analysis.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("✓ Successfully fixed all dependencies!")
print("  - Checks for area_type column")
print("  - Applies classification if needed")
print("  - Creates df_enroll_clean automatically")
